# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xxw/unix/json-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xxw/unix/json-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xxw/unix/json-master/CMakeFiles /home/xxw/unix/json-master/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xxw/unix/json-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named leptjson_test

# Build rule for target.
leptjson_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 leptjson_test
.PHONY : leptjson_test

# fast build rule for target.
leptjson_test/fast:
	$(MAKE) -f CMakeFiles/leptjson_test.dir/build.make CMakeFiles/leptjson_test.dir/build
.PHONY : leptjson_test/fast

#=============================================================================
# Target rules for targets named leptjson

# Build rule for target.
leptjson: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 leptjson
.PHONY : leptjson

# fast build rule for target.
leptjson/fast:
	$(MAKE) -f CMakeFiles/leptjson.dir/build.make CMakeFiles/leptjson.dir/build
.PHONY : leptjson/fast

leptjson.o: leptjson.c.o

.PHONY : leptjson.o

# target to build an object file
leptjson.c.o:
	$(MAKE) -f CMakeFiles/leptjson.dir/build.make CMakeFiles/leptjson.dir/leptjson.c.o
.PHONY : leptjson.c.o

leptjson.i: leptjson.c.i

.PHONY : leptjson.i

# target to preprocess a source file
leptjson.c.i:
	$(MAKE) -f CMakeFiles/leptjson.dir/build.make CMakeFiles/leptjson.dir/leptjson.c.i
.PHONY : leptjson.c.i

leptjson.s: leptjson.c.s

.PHONY : leptjson.s

# target to generate assembly for a file
leptjson.c.s:
	$(MAKE) -f CMakeFiles/leptjson.dir/build.make CMakeFiles/leptjson.dir/leptjson.c.s
.PHONY : leptjson.c.s

leptjsontest.o: leptjsontest.c.o

.PHONY : leptjsontest.o

# target to build an object file
leptjsontest.c.o:
	$(MAKE) -f CMakeFiles/leptjson_test.dir/build.make CMakeFiles/leptjson_test.dir/leptjsontest.c.o
.PHONY : leptjsontest.c.o

leptjsontest.i: leptjsontest.c.i

.PHONY : leptjsontest.i

# target to preprocess a source file
leptjsontest.c.i:
	$(MAKE) -f CMakeFiles/leptjson_test.dir/build.make CMakeFiles/leptjson_test.dir/leptjsontest.c.i
.PHONY : leptjsontest.c.i

leptjsontest.s: leptjsontest.c.s

.PHONY : leptjsontest.s

# target to generate assembly for a file
leptjsontest.c.s:
	$(MAKE) -f CMakeFiles/leptjson_test.dir/build.make CMakeFiles/leptjson_test.dir/leptjsontest.c.s
.PHONY : leptjsontest.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... leptjson_test"
	@echo "... leptjson"
	@echo "... leptjson.o"
	@echo "... leptjson.i"
	@echo "... leptjson.s"
	@echo "... leptjsontest.o"
	@echo "... leptjsontest.i"
	@echo "... leptjsontest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

